[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 600
startCommand = "gunicorn --bind 0.0.0.0:${PORT:-8080} --timeout 120 --workers 1 server:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
